import '../models/equipment.dart';
import 'api_service.dart';

class EquipmentService {
  final ApiService _api;

  EquipmentService(this._api);

  Future<String> createEquipment({
    required String name,
    required EquipmentType type,
    String? manufacturer,
    String? model,
    String? serialNumber,
    DateTime? purchaseDate,
    String? notes,
  }) async {
    final equipment = Equipment(
      id: '', // Will be generated by backend
      name: name,
      type: type,
      manufacturer: manufacturer,
      model: model,
      serialNumber: serialNumber,
      purchaseDate: purchaseDate,
      notes: notes,
    );

    final created = await _api.createEquipment(equipment);
    return created.id;
  }

  Future<List<Equipment>> getAllEquipment() async {
    return await _api.getAllEquipment();
  }

  Future<Equipment?> getEquipmentById(String id) async {
    return await _api.getEquipmentById(id);
  }

  Future<void> updateEquipment(Equipment equipment) async {
    await _api.updateEquipment(equipment);
  }

  Future<void> deleteEquipment(String id) async {
    await _api.deleteEquipment(id);
  }

  List<Equipment> filterByType(List<Equipment> equipment, EquipmentType type) {
    return equipment.where((e) => e.type == type).toList();
  }
}
